# coding: utf-8

"""
    Alfresco Content Services REST API

    **Search API**  Provides access to the search features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import BaseModel, StrictStr
from pydantic import Field
from alfresco_search_api_client.models.generic_bucket_bucket_info import GenericBucketBucketInfo
from alfresco_search_api_client.models.generic_metric import GenericMetric
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class GenericBucket(BaseModel):
    """
    A bucket of facet results
    """ # noqa: E501
    label: Optional[StrictStr] = Field(default=None, description="The bucket label")
    filter_query: Optional[StrictStr] = Field(default=None, description="The filter query you can use to apply this facet", alias="filterQuery")
    display: Optional[Union[str, Any]] = Field(default=None, description="An optional field for additional display information")
    metrics: Optional[List[GenericMetric]] = Field(default=None, description="An array of buckets and values")
    facets: Optional[List[Union[str, Any]]] = Field(default=None, description="Additional list of nested facets")
    bucket_info: Optional[GenericBucketBucketInfo] = Field(default=None, alias="bucketInfo")
    __properties: ClassVar[List[str]] = ["label", "filterQuery", "display", "metrics", "facets", "bucketInfo"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GenericBucket from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in metrics (list)
        _items = []
        if self.metrics:
            for _item in self.metrics:
                if _item:
                    _items.append(_item.to_dict())
            _dict['metrics'] = _items
        # override the default output from pydantic by calling `to_dict()` of bucket_info
        if self.bucket_info:
            _dict['bucketInfo'] = self.bucket_info.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of GenericBucket from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "label": obj.get("label"),
            "filterQuery": obj.get("filterQuery"),
            "display": obj.get("display"),
            "metrics": [GenericMetric.from_dict(_item) for _item in obj.get("metrics")] if obj.get("metrics") is not None else None,
            "facets": obj.get("facets"),
            "bucketInfo": GenericBucketBucketInfo.from_dict(obj.get("bucketInfo")) if obj.get("bucketInfo") is not None else None
        })
        return _obj


