# coding: utf-8

"""
    Alfresco Content Services REST API

    **Search API**  Provides access to the search features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from alfresco_search_api_client.models.generic_bucket import GenericBucket

class TestGenericBucket(unittest.TestCase):
    """GenericBucket unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenericBucket:
        """Test GenericBucket
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GenericBucket`
        """
        model = GenericBucket()
        if include_optional:
            return GenericBucket(
                label = '',
                filter_query = '',
                display = alfresco_search_api_client.models.display.display(),
                metrics = [
                    alfresco_search_api_client.models.generic_metric.GenericMetric(
                        type = '', 
                        value = alfresco_search_api_client.models.value.value(), )
                    ],
                facets = [
                    None
                    ],
                bucket_info = alfresco_search_api_client.models.generic_bucket_bucket_info.GenericBucket_bucketInfo(
                    start = '', 
                    start_inclusive = True, 
                    end = '', 
                    end_inclusive = True, )
            )
        else:
            return GenericBucket(
        )
        """

    def testGenericBucket(self):
        """Test GenericBucket"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
