# coding: utf-8

"""
    Alfresco Content Services REST API

    **Search API**  Provides access to the search features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from alfresco_search_api_client.models.request_defaults import RequestDefaults

class TestRequestDefaults(unittest.TestCase):
    """RequestDefaults unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestDefaults:
        """Test RequestDefaults
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestDefaults`
        """
        model = RequestDefaults()
        if include_optional:
            return RequestDefaults(
                text_attributes = [
                    'cm:content'
                    ],
                default_fts_operator = 'AND',
                default_fts_field_operator = 'AND',
                namespace = 'cm',
                default_field_name = 'TEXT'
            )
        else:
            return RequestDefaults(
        )
        """

    def testRequestDefaults(self):
        """Test RequestDefaults"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
