# coding: utf-8

"""
    Alfresco Content Services REST API

    **Search API**  Provides access to the search features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from alfresco_search_api_client.models.request_stats import RequestStats

class TestRequestStats(unittest.TestCase):
    """RequestStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestStats:
        """Test RequestStats
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestStats`
        """
        model = RequestStats()
        if include_optional:
            return RequestStats(
                field = '',
                label = '',
                min = True,
                max = True,
                sum = True,
                count_values = True,
                missing = True,
                mean = True,
                stddev = True,
                sum_of_squares = True,
                distinct_values = True,
                count_distinct = True,
                cardinality = True,
                cardinality_accuracy = 1.337,
                exclude_filters = [
                    ''
                    ],
                percentiles = [
                    1.337
                    ]
            )
        else:
            return RequestStats(
        )
        """

    def testRequestStats(self):
        """Test RequestStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
